### PR TITLE
Enums fix

### PR DESCRIPTION
**Pull request by GrantHoffman**

### CODE REVIEW

**Comment by sinelaw** [comment]
What issue is the nuget commit fixing?
We're not supposed to distribute nuget with the source of a package...

**Comment by sinelaw** [comment]
Thanks for this!
Can you give an example of the enum problem?

**Comment by GrantHoffman** [comment]
Nuget: When downloading the project for the first time you get compilation errors, 

Enums:

 say you have an enum 

`public enum EthnicCode
      {
             Poorly_Named
      }`

and you want to override the name it to be PoorlyNamed or even just Poorly

**Comment by hadason** [comment]
I don't see a reason to include the nuget files in the solution. If you have an issue with the nuget configuration in the CSProj (or .sln) file then solve it there (for example, remove the problematic line)

**Comment by hadason** [comment]
Regarding the enum names, I think it will be better to add a Type parameter to the `TryGetPropertyName` and just call it for the enum names as well. this way we'll have one method that handles with custom property names (an enum value is eventually a property of the enum)

**Comment by hadason** [comment]
What about removing the Nuget dependencies?

**Comment by GrantHoffman** [comment]
I finished fixing the csproj file, you should be able to compile

**Pull request merged**
